variables:
  # KUBE_INGRESS_BASE_DOMAIN is the application deployment domain and should be set as a variable at the group or project level.
  # KUBE_INGRESS_BASE_DOMAIN: domain.example.com
  POSTGRES_ENABLED: "false"
  HELM_SCALE_EXTRA_ARGS: --set postgresql.enabled="false" 
  ROLLOUT_RESOURCE_TYPE: deployment
  DOCKER_TLS_CERTDIR: ""  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

stages:
    - build

build_app:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  tags:
    - kubernetes
  script:
    - dotnet nuget add source --username eric.sheris --password $NUGET_PAT --store-password-in-clear-text --name gitlab "https://gitlab.cdrentertainment.com/api/v4/groups/5/-/packages/nuget/index.json"
    - dotnet restore
    - dotnet build --no-restore --configuration Release
    - echo $(ls bin/Release/net5.0/)
    - dotnet nuget push bin/Release/net5.0/package.nupkg --source gitlab
  artifacts:
    paths:
      - bin/Release/net5.0/*