variables:
  # KUBE_INGRESS_BASE_DOMAIN is the application deployment domain and should be set as a variable at the group or project level.
  # KUBE_INGRESS_BASE_DOMAIN: domain.example.com
  POSTGRES_ENABLED: "false"
  HELM_SCALE_EXTRA_ARGS: --set postgresql.enabled="false"
  ROLLOUT_RESOURCE_TYPE: deployment
  DOCKER_TLS_CERTDIR: "" # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

stages:
- build
- scan

build_app:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  tags:
  - kubernetes
  script:
  - dotnet nuget add source --username $BOT_USER --password $BOT_PAT --store-password-in-clear-text --name rumble-core-gitlab "https://gitlab.cdrentertainment.com/api/v4/projects/26/packages/nuget/index.json"
  - dotnet nuget add source --username $BOT_USER --password $BOT_PAT --store-password-in-clear-text --name rumble-json-gitlab "https://gitlab.cdrentertainment.com/api/v4/projects/74/packages/nuget/index.json"
  - dotnet restore
  - dotnet build --no-restore --configuration Release
  - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --username $BOT_USER --password $BOT_PAT --store-password-in-clear-text --name gitlab
  - dotnet nuget push "$PWD/bin/Release/*.nupkg" --source gitlab

sonarqube-check:
  stage: scan
  image: mcr.microsoft.com/dotnet/sdk:8.0
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
    - .sonar/cache
  script:
  - "apt-get update"
  - "apt-get install --yes openjdk-17-jre"
  - "dotnet tool install --global dotnet-sonarscanner"
  - dotnet nuget add source --username $BOT_USER --password $BOT_PAT --store-password-in-clear-text --name gitlab "https://gitlab.cdrentertainment.com/api/v4/projects/14/packages/nuget/index.json"
  - dotnet nuget add source --username $BOT_USER --password $BOT_PAT --store-password-in-clear-text --name platform "$CI_SERVER_URL/api/v4/groups/5/-/packages/nuget/index.json"
  - dotnet nuget add source --username $BOT_USER --password $BOT_PAT --store-password-in-clear-text --name tower "$CI_SERVER_URL/api/v4/groups/6/-/packages/nuget/index.json"
  - dotnet restore
  - "export PATH=\"$PATH:$HOME/.dotnet/tools\""
  - "dotnet sonarscanner begin /o:\"rstudios\" /k:\"rstudios_${CI_PROJECT_TITLE}\" /d:sonar.login=\"$SONAR_TOKEN\" /d:\"sonar.host.url=$SONAR_HOST_URL\" "
  - "dotnet build"
  - "dotnet sonarscanner end /d:sonar.login=\"$SONAR_TOKEN\""
  allow_failure: true
  only:
  - merge_requests
  - main
