variables:
  # KUBE_INGRESS_BASE_DOMAIN is the application deployment domain and should be set as a variable at the group or project level.
  # KUBE_INGRESS_BASE_DOMAIN: domain.example.com
  POSTGRES_ENABLED: "false"
  HELM_SCALE_EXTRA_ARGS: --set postgresql.enabled="false" 
  ROLLOUT_RESOURCE_TYPE: deployment
  DOCKER_TLS_CERTDIR: ""  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

stages:
    - build

build_app:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  tags:
    - kubernetes
  script:
    - dotnet nuget add source --username $BOT_USER --password $BOT_PAT --store-password-in-clear-text --name gitlab "https://gitlab.cdrentertainment.com/api/v4/projects/26/packages/nuget/index.json"
    - dotnet restore
    - dotnet build --no-restore --configuration Release
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --username $BOT_USER --password $BOT_PAT --store-password-in-clear-text --name gitlab
    - dotnet nuget push "$PWD/bin/Release/*.nupkg" --source gitlab
